Task 1
RAF-SI-2022/Banka-1-Frontend pull request #21
Opened 2023-03-10 17:32 UTC by vstanisic4619rn

2023-03-10 18:40 UTC, VukV requested changes
Struktura dizajna nije ispostovana. Ne trazi se preciznost u milimetar, ali ovo maksimalno odstupa od strukture.
Button nije koriscen onaj koji je po dizajnu, i koji su koristili svi ostali. Vec sam naglasio da se on nalazi u HomeComponent-u, samo je potrebno kopirati ga.
Forma moze da se menja, a naglaseno je da su label-i zakljucani, osim imena, prezimena i telefona, samo oni se menjaju.
Poziv funkcije iz servisa je pogresan, to je funkcija koju zove admin da kreira novog korisnika, ovo je izmena SOPSTVENOG profila.
Molim te citaj dodeljeni issue!

2023-03-10 23:34 UTC, vstanisic4619rn commented
Bug fix

2023-03-11 10:41 UTC, VukV requested changes
Struktura i dalje nije ispoštovana, molim te radi po uzoru na poslatu sliku.
Poruka o validaciji je em na pogrešnom mestu, em se prikazuje, treba da bude skrivena, i da nema template tekst "poruka o validaciji (inicijalno skriveno)"...
Button je na pogrešnom mestu, i validacija treba da bude ispod njega.
Naslovi ne treba da budu velikim slovima, pokušavamo da se pridržavamo uniformnog dizajna. Takođe, nisu korišćene boje naznačene u globalnom CSS fajlu.
Placeholder-i forme su na engleskom, radimo na srpskom, kao što je po urađenom dizajnu.
Postoji link ka početnoj stranici, a ne treba da bude tu.
Div sa formom je crn, ne treba da ima boju.
Nigde se ne poziva inicijalni fetch za podatke o korisniku koji treba da popune polja forme.
changePasswordRequest() je dupla funkcija, ona već postoji unutar UserService-a.
Takođe, postoji div sa nekakvim ikonicama koje vode na početnu stranicu??

Molim te da pratiš date instrukcije!

2023-03-11 20:01 UTC, VukV requested changes
Čekam finalne izmene o kojima smo pričali na Mattermostu kako bih mogao da uradim merge.

2023-03-12 10:38 UTC, VukV commented
Task kasni, radim merge sa dosadasnjim delom taska, i isti preuzimam da zavrsim.

2023-03-12 10:38 UTC, merged